### ISSUE TITLE
WPML - SELLER DASHBOARD - Subscriptions - Various Settings not copied to the translated Dokan subcription

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan-wpml#38]
After opening a customer support ticket first (#41668 — WPML - SELLER DASHBOARD - Subscriptions - Duration of pack not shown), this issue has been recognized as a plugin-level issue by Yeasin Afrat.

The billing period /month is not shown in the translated versions and I can't find the string either as you can see here:

https://ibb.co/mHq3ndP
https://ibb.co/Jz6ghyY

The subscription products have been translated exactly like the other type of products using WPML editor, and everything works as it is supposed too, except the Duration of Dokan subscriptions which is not shown at all.

**Comment by Sophie-2e** [comment]
Note, here are all the info that are not being copied on the translated versions of the subscription: 

- [ ] categories 
- [ ] number of images 
- [ ] number of products 
- [ ] Admin Commission settings 
- [ ] Product type 
- [ ] Recurring payment settings

**Comment by shohag121** [comment]
Hello @Sophie-2e,

I've added a plugin-level fix for this issue.

Thank you for reporting the issue to us.

**Comment by Sophie-2e** [comment]
Hello @shohag121, so efficient and fast 🤩 Thanks a lot for taking care of this, you rock 🙌

Did you add the code to the staging website, and if yes coud you indicate in which folder I need to replace/add the code for the live website?

Finally, will the fix be released in the next Dokan update :) ?

**Comment by shohag121** [comment]
It will be available in the next Dokan WPML release.

**Comment by Sophie-2e** [comment]
Awesome news @shohag121! Thank you so much for your hard work, you rock!

**Comment by Sophie-2e** [comment]
Tested the last Dokan WPML updates, and indeed now it works like a charm! 🎉 thank you so much @shohag121 ! You rock!
