### ISSUE TITLE
DOKAN PRO - New Menu Manager Settings - Menu Items Not translatable for now (WPML)

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan-wpml#54]
FOLLOWING UP ON SUPPORT TICKET #50056 with Sazzat

Just tried your New Menu Manager Settings but as soon as modified the order of the menu items, I am losing the translation of the items and get the english default language in french and dutch vendor dashboard. Seems it miss translation settings on it as I cannot find the strings even after scanning Dokan plugins in WPML : https://www.loom.com/share/43b906fa4bd34cdc8b0c06b2549d968b

**Comment by Sophie-2e** [comment]
Hello @aihimel actually I found out how to translate them, if someone faces the same issue in the future, here the solution:

1. Make your modifications to the menu in Dokan > Settings > Menu Manager Settings
2. Go to WPML > Theme and plugins localization > Rescan Dokan, Dokan Pro and Dokan WPML
3. Go to WPML > Strings Translation > search for a term in your menu > 
4. Use the option "Can't find the strings you're looking to translate?" > look for the strings [dokan_menu_manager][dashboard_menu_manager][left_menus] => ONLY the 'menu_manager_title' strings needs to be translated (so NOT 'title' nor 'previous_title')

**Comment by aihimel** [comment]
Hello @Sophie-2e,
Thanks for sharing your findings. We would add a documentation about this.
Thanks
