### ISSUE TITLE
⚠️⚠️ SELLER REGISTRATION FORM > Shop url > Translated forms > double //

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan-wpml#59]
I notice an issue with the shop url in the vendor registration form www.website.com/shop/name-shop-vendor in other languages where a double // is added to the store url such as www.website.com/fr//shop/name-shop-vendor or www.website.com/nl//shop/name-shop-vendor. Please review this image: 
<img width="632" alt="Screenshot 2024-03-30 at 11 18 45" src="https://github.com/getdokan/dokan-wpml/assets/131655229/6d2ce489-528a-4af5-8726-fbd2dfdbf65f">

**Comment by Mohaiminulislam1989** [comment]
@shams-sadek1981 vai, Please assign this to the developer

**Comment by Sophie-2e** [comment]
PS: @shams-sadek1981 still bugging with Dokan & Dokan Pro 3.11.0 when will this be fixed?

**Comment by Sophie-2e** [comment]
So when this is going to be fixed? Still Buging with Dokan 3.11.2 and Pro 3.11.1 It might just be a small error in the code that is adding a / Please update me thanks

@shams-sadek1981 @Mohaiminulislam1989

**Comment by Sophie-2e** [comment]
Hello @shohag121 @MdAsifHossainNadim @mrabbani hope you're well. Just tested the fix released in Dokan 3.11.4 : 'Shop URL rendered double slash when using WPML on vendor registration' does not work. Still does not work even with Dokan WPML Integration Version 1.1.5:

![Screenshot 2024-07-17 at 17 27 52](https://github.com/user-attachments/assets/0ca29537-61eb-4761-9589-8fcacfafd985)

Please reopen this GitHub, and test yourself.

**Comment by MdAsifHossainNadim** [comment]
@Sophie-2e The problem does not reproduce on my end. This could be a cache issue. Please resync your strings, clear the cache and test it again. Then, please provide us with a screencast if you can reproduce this issue.

![Screenshot at Jul 25 14-00-14](https://github.com/user-attachments/assets/a8d1cf11-a6a9-4fd3-babc-d01d53d8784b)

**Comment by Sophie-2e** [comment]
@MdAsifHossainNadim no cache issue, no sync issue either as I already did these manipulations many times since I updated. You will see proof in these videos: 
- No plugin excl dokan/woo/elementor (as page is build with Dokan Shortcode in Elementor Shortcode): https://www.loom.com/share/e1d99b74ee9c4f9ebcde14de9d2a98f2?sid=6f965887-5638-4869-9fe1-ed4051e1209e
- No plugin excl dokan/woo/elementor + default Storefront theme: https://www.loom.com/share/b429f49ead6249c181a0e4a9d0aab5d7?sid=d5eb6f2e-6fb8-4687-b456-3cf1e8d4121b

Are you sure to test with the shortcode: [dokan-vendor-registration] ?
![Screenshot 2024-07-25 at 12 00 56](https://github.com/user-attachments/assets/e6470865-b328-4585-a3b6-7d9a8838191d)

**Comment by Sophie-2e** [comment]
@MdAsifHossainNadim @Mohaiminulislam1989 No solution does not work, review the comment here https://github.com/getdokan/dokan/pull/2319#issuecomment-2262719788

**Comment by Mohaiminulislam1989** [comment]
> @MdAsifHossainNadim @Mohaiminulislam1989 No solution does not work, review the comment here [getdokan/dokan#2319 (comment)](https://github.com/getdokan/dokan/pull/2319#issuecomment-2262719788)

@MdAsifHossainNadim please check
