### ISSUE TITLE
⚠️⚠️ SELLER VERIFICATION > Email sent to Vendor - Seller Verification Status Updated Template: Subject Email + Document type + Status not translated

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan-wpml#61]
Following up customer support ticket #55561

In the Seller Verification Status Updated Template;

- [x]  the subject email while this string is translated in WPML 
- [x] the status are not translated while this string is translated in WPML 
- [ ] the Document Type is not translated and the string cannot be found in WPML strings translation even after rescanning theme and plugins.

Please review this video from 7:00 min to 10:25 min: which you can find in customer support ticket #55561

The subject used to work before the latest dokan update and I remember reporting the other issues for the status and document type last year already. 

Please check it out and let me know how to fix it.

**Comment by Sophie-2e** [comment]
With Dokan 3.11, issues still there

**Comment by Sophie-2e** [comment]
With new verification module solved some issues but as the title and the helper text are not translatable in the new Verification Module, the document title is still not translated in the email, nor in the verification tab in Vendor Dashboard > Settings > Verification

**Comment by pronob1010** [comment]
@imtiaz-pranto Bhai, the helper text is translateable now, 
![Image](https://github.com/user-attachments/assets/3da58e3f-43ac-42cc-8db9-27a64e1219d6)

@StalinDurjo Bhai you have tested this issue and is this PR still pending release?

**Comment by StalinDurjo** [comment]
I have tested this PR: [ #3754](https://github.com/getdokan/dokan-pro/pull/3754), which is released.

**Comment by pronob1010** [comment]
@imtiaz-pranto bhai this issue is not relevant anymore. If there is nothing left, can we close this?

**Comment by imtiaz-pranto** [comment]
The issue seems to be addressed. Closing this issue for now.
