### ISSUE TITLE
⚠️⚠️⚠️ SELLER PACKS SUBSCRIPTION - Email "Vendor Dokan Vendor Enable" email template > not translated - even if vendor orders pack in another language and has his default language set up to it

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan-wpml#64]
Following up on customer support ticket #55591

I noticed a bug with the SELLER PACKS SUBSCRIPTION for the Email "Vendor Dokan Vendor Enable" email template > even if email is translated, for example for french, if vendor orders the pack in French and has his default language as French, he still receives the email in English (default website language) instead of french.

In this video you can see that he has ordered in French from 21min: ask video in customer support ticket #55591

And in this video (no sound) you can see that the email settings and content are translated and that the user default language is set up to french but the email received is in english: ask video in customer support ticket #55591

Please check it out and fix it

**Comment by Sophie-2e** [comment]
Still not with Dokan 3.11.0

**Comment by Sophie-2e** [comment]
and still bugging with dokan 3.11.1...

**Comment by Sophie-2e** [comment]
2 months later still no news on when this will be fixed...

**Comment by Sophie-2e** [comment]
...Update Dokan 3.11.4 + Pro 3.11.3, still not fixed. Only received email in website default language even if email content is translated.

**Comment by Sophie-2e** [comment]
...Update Dokan 3.11.5 + Pro 3.11.4, still not fixed. Could you please assign someone @imtiaz-pranto? Thanks for your help

**Comment by Sophie-2e** [comment]
Hello @imtiaz-pranto can you help me get this resolved? It is quite urgent but no one seems to be assigned even after that the Support Team has reported the issue to the dev team several times on their side too over the last few months. Thanks for your hep 🙌

**Comment by imtiaz-pranto** [comment]
@MdAsifHossainNadim bhai, please consult with @getdokan/support for this issue.

**Comment by imtiaz-pranto** [comment]
@pronob1010 bhai, please consult with @getdokan/support for solving this issue.

**Comment by pronob1010** [comment]
@imtiaz-pranto Thank you for assigning me. Let me replicate and hope you will receive an update soon.

**Comment by pronob1010** [comment]
> @pronob1010 @MdAsifHossainNadim Bhai, Did you follow [this ](https://wpml.org/documentation/related-projects/woocommerce-multilingual/how-to-translate-woocommerce-emails/) documentation?

Yes, I have checked out all the mentioned areas. The main issue is that `setup_locale` cannot detect the vendors' local language. I attempted to retrieve the preferred language from the user data manually.

```
$vendor_locale = get_user_meta( $seller_id, 'preferred_language', true );

if ( ! empty( $vendor_locale ) && $vendor_locale !== get_locale() ) {
        switch_to_locale( $vendor_locale );
}
```

However, this approach also did not work.

**Comment by Sophie-2e** [comment]
Hello @pronob1010 @shohag121

Still bugging with Dokan 3.12.5. When can we except a fix?

**Comment by pronob1010** [comment]
@Sophie-2e I've recently been assigned to this issue and noticed it's a corner case. I'm working on it and expect to have it resolved soon. I apologize for the delay, and thank you for your patience.

**Comment by pronob1010** [comment]
@imtiaz-pranto Bhai, I tried to reproduce this issue and I think this issue has been resolved with a previous PR.

![Image](https://github.com/user-attachments/assets/1abca324-eca0-4551-9999-cd3193a5a905)
![Image](https://github.com/user-attachments/assets/f1693063-3faf-438d-b978-f9ea05deba8f)

Could you please check? Let me know if I missed anything.

**Comment by pronob1010** [comment]
@StalinDurjo Bhai is this still an issue?

**Comment by StalinDurjo** [comment]
Can't provide confirmation as I haven't done any tests related to it recently.

**Comment by pronob1010** [comment]
@imtiaz-pranto bhai, this issue is not valid anymore, and the PR has been released before. So, you can close this issue. Please let me know if I missed anything. 

![Image](https://github.com/user-attachments/assets/00bb145f-e7bf-4801-84c1-78ec6efee7a9)

**Comment by imtiaz-pranto** [comment]
Closing this issue as this issue was resolved.
