### ISSUE TITLE
DOKAN SELLER ADDRESS FIELDS - CITY SHOULD BE A DEFAULT FIELDS LIKE THE COUNTRY so we can translate address in front end

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan-wpml#71]
Hello Team Dokan,

If the Country field works well in the Seller Address, it does not for the City which is manually added via text by the sellers, while he needs to select a country field (that indeed can be translated in WPML strings).

You can see the seller address on his store and in the store lists and in the My Account > Followers:

You can see in the image below tha sellers added the city in english 'Brussels', while in french it should be 'Bruxelles' and Dutch 'Brussel':

![Screenshot 2024-04-10 at 14 56 15](https://github.com/getdokan/dokan-wpml/assets/131655229/aba24e4e-155c-4e19-b42f-49c88d830f6d)
![Screenshot 2024-04-10 at 14 55 59](https://github.com/getdokan/dokan-wpml/assets/131655229/b114dc01-197e-420e-9f9c-c637edfff1f8)
![Screenshot 2024-04-10 at 14 55 43](https://github.com/getdokan/dokan-wpml/assets/131655229/0de33a75-31ed-4285-ae3c-c2230d5c882a)

This result in the address being half translated in front end where only the country will be in the right language but the city will be written as the seller has added it in the Seller Registration form or in Vendor Dashboard > Settings > Store > Address or in the Vendor Wizard or in the Verification Module (Vendor Dashboard > Settings > Verification).

This feature will also reduce the errors in address registration for both customers, sellers, and order delivery.

**Comment by pronob1010** [comment]
@imtiaz-pranto Bhai, I have discussed this with @jamil-mahmud Bhai. As WooCommerce doesn't support this, we won't be adding support for full address translation and I also investigated the given scenario there. The state and country name are working as expected, so this issue may not be valid anymore. 

![Image](https://github.com/user-attachments/assets/121a8eeb-6588-4649-a50f-2d7e1eab491d)

**Comment by jamil-mahmud** [comment]
@pronob1010 vai, according to your finding from our side we won't further progress on this unless heavy requirement  comes on this. That is why closing this according to current solution
