### ISSUE TITLE
⚠️⚠️ DOKAN/RANKMATH/WPML - SELLER DASHBOARD - ADD / EDIT PRODUCT - SEO: RankMath Module translation missing

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan-wpml#72]
I need an update on it fast to know if I can keep RankMath or revert to YoastSEO (even though I would rather keep RankMath which has better features for the global website).

Following up on Dokan Support Ticket #56071 

Need help with translation of RankMath Module in Dokan Vendor Dashboard with WPML.

1. Lots of fields are not translatable (not found in WPML strings at all even after rescanning all themes and plugins)
2. Or they are translated in WPML strings but not shown in the front end (both text domain dokan/dokan-lite and rank-math)

I was using YoastSEO previously and could translate all the fields with WPML strings in the seller dashboard...I replaced it as it is better than Yoast and was supposed to be integrated with Dokan, but now I am not so sure...

Please review the video sent in Dokan support ticket #56071 and let me know if it is possible to translate the module, and if it is supposed to, if the translation issue lies with Dokan and if Dokan can help fix the translation issues in the Vendor Dashboard? 

I opened a ticket with RankMath too for your info but so far seems like they cannot fix it: https://support.rankmath.com/ticket/dokan-rankmath-wpml-seller-dashboard-add-edit-product-seo-rankmath-modu/

**Comment by Sophie-2e** [comment]
Hello @mrabbani and @MdAsifHossainNadim hope you are well :) Is this plan for a future update and if yes for which quarter? Thank for your help

**Comment by Sophie-2e** [comment]
@mrabbani @MdAsifHossainNadim any news?

**Comment by MdAsifHossainNadim** [comment]
@Sophie-2e RankMath module content in the Seller Dashboard is being rendered via the RankMath assets on the Seller Products screen. It is not possible to translate RankMath content from Dokan.

Here we are using RankMath assets `e.g. classic.js, metabox.css etc.` to render the RankMath content on the seller product page. We need to ensure the RankMath contents are translatable via WPML from their end.

**Comment by Sophie-2e** [comment]
@MdAsifHossainNadim you already have RankMath's answer: https://support.rankmath.com/ticket/dokan-rankmath-wpml-seller-dashboard-add-edit-product-seo-rankmath-modu/ as you have seen here: https://github.com/getdokan/dokan-wpml/issues/72#issue-2242053834

So what now, because indeed RankMath is right, it works like a charm in the admin, so there is no issue with RankMath translation but again, an issue with Dokan compatibility with RankMth and WPML.

So 5 months later, we are back to: https://github.com/getdokan/dokan-wpml/issues/72#issue-2242053834. 
So what now @mrabbani, @MdAsifHossainNadim, @imtiaz-pranto?

**Comment by prottoy210385** [comment]
@jamil-mahmud bhai, please take a look at this issue as soon as possible!

**Comment by jamil-mahmud** [comment]
@prottoy210385 vai, 

Kindly let our client know about this particular PR [Fix PR](https://github.com/getdokan/dokan-pro/pull/3835) which our client pull and check if it resolves on the asking issue. If it conflicts then that's dependable on WPML end, not on our side. Kindly follow up with client to check and afterwards if any discussion is required we will proceed again.
