### ISSUE TITLE
⚠️⚠️ SELLER REGISTRATION FORM > Shop url > Translated forms > double // - Reopening #59

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan-wpml#79]
Hello, this issue has been closed with the supposed fix released in last Dokan update but does not work.

Support ticket: https://app.dokan.co/support/54350 + https://app.dokan.co/support/65773

Test with dokan Dokan 3.11.4 + Pro 3.11.3 : 'Shop URL rendered double slash when using WPML on vendor registration' => Still does not work even with Dokan WPML Integration Version 1.1.5: https://github.com/getdokan/dokan-wpml/issues/59#issuecomment-2233600772

Please check it out again.

**Comment by Mohaiminulislam1989** [comment]
@MdAsifHossainNadim, please check

**Comment by Sophie-2e** [comment]
@MdAsifHossainNadim  @Mohaiminulislam1989  check this before adding your fix to the update, still one issue with new code: https://github.com/getdokan/dokan/pull/2319#issuecomment-2262719788

**Comment by Mohaiminulislam1989** [comment]
> @MdAsifHossainNadim @Mohaiminulislam1989 check this before adding your fix to the update, still one issue with new code: [getdokan/dokan#2319 (comment)](https://github.com/getdokan/dokan/pull/2319#issuecomment-2262719788)

@MdAsifHossainNadim

**Comment by Sophie-2e** [comment]
Hi guys, just tested with the latest Dokan update - 3.11.5 - and thank you so much @MdAsifHossainNadim! It works like a charm now, 0 issue left 👌💯🙌 Thanks to @Mohaiminulislam1989 too for following up on the bug resolution 👌 

Very good teamwork guys 💯🎉
