### ISSUE TITLE
Dokan Pro: Products not syncing and updating in the secondary language

### ISSUE THREAD

**Issue by tanjiralmamun** [getdokan/dokan-wpml#8]
**Description of the Bug:**
Products are not being synced and updated in the secondary language after updating from the primary language's quick edit option. Also, if vendors update Dokan Pro-related fields from the "Edit Product" page, those are not being synced and updated in the second language.

Only the Dokan Lite's (Free) product section fields are being synced and updated in the secondary language when a vendor edits/updates those from the edit product page.

**How to reproduce:**
- Translate a product in the secondary language
- Edit product from vendor dashboard quick edit option
- Update the product and check it to the secondary language vendor dashboard
- Product didn't sync in the secondary language
- Edit the product from the edit product page (Like price/SKU)
- Product synced and updated in a secondary language
- Edit one of Dokan Pro's section fields from the edit product page
- Now, check the product in the secondary language
- Product didn't sync in a secondary language

**Expected Behaviour:**
Products should be synced and updated in the secondary language.

**Comment by nayemDevs** [comment]
A few details to note - 

When you install WPML it has the option to confirm "If you want to show the product in both languages if not translated on both langauge". That means if I upload a product in English and If the user switches to the Arabic language then the English version will show.

This does not happen when the vendor is uploading and the settings of WPML totally ignored.

**Comment by tanjiralmamun** [comment]
> A few details to note -
> 
> When you install WPML it has the option to confirm "If you want to show the product in both languages if not translated on both language". That means if I upload a product in English and If the user switches to the Arabic language then the English version will show.
> 
> This does not happen when the vendor is uploading and the settings of WPML totally ignored.

@nayemDevs, this feature seems working properly now. So, now we need to fix the product syncing issue.

**Comment by Mohaiminulislam1989** [comment]
@nurul-umbhiya vai please check this

**Comment by Mohaiminulislam1989** [comment]
@nurul-umbhiya vai. please check this issue.

**Comment by nurul-umbhiya** [comment]
@Mohaiminulislam1989 will check this issue today inshaAllah

**Comment by nurul-umbhiya** [comment]
Since we are using update_post_meta() methods for updating the product meta's, the default hook wasn't triggered. This will be fixed automatically once we finish the Product Form Customizer feature. Also, fields (custom meta) that are coming from Dokan Pro, need to enable syncing for them from the WPML settings.

<img width="1258" alt="Screenshot 2024-03-07 at 3 01 39 PM" src="https://github.com/getdokan/dokan-wpml/assets/10240343/70e89b63-5906-459e-a02d-5625b7693efe">

**Comment by shohag121** [comment]
* Related: https://github.com/getdokan/dokan/issues/2122
