### ISSUE TITLE
Dokan WPML Guides

### ISSUE THREAD

**Issue by MdAsifHossainNadim** [getdokan/dokan-wpml#90]
- [Text Detected in WPML String List but Not Translating after saving from Menu Manager](https://github.com/getdokan/dokan-wpml/issues/90#issuecomment-2477924064)
- [JS String translation issue](https://github.com/getdokan/dokan-wpml/issues/90#issuecomment-2477924068) 
- [Dynamic text translation not working for large content](https://github.com/getdokan/dokan-wpml/issues/90#issuecomment-2477924070)
- [Custom String Translation Guide](https://github.com/getdokan/dokan-wpml/issues/90#issuecomment-2477924073)
- [Translate product categories for vendor product add/edit page by WPML](https://github.com/getdokan/dokan-wpml/issues/90#issuecomment-2477924076)

**Comment by jamil-mahmud** [comment]
@MdAsifHossainNadim vai,

Kindly convert this guideline into a Wiki in WPML Repo as per our discussion.

**Comment by MdAsifHossainNadim** [comment]
@jamil-mahmud Brother, Here is our [wiki link](https://github.com/getdokan/dokan-wpml/wiki/Dokan-WPML-Guides)
